networks:
  everlock-network:
    driver: bridge

services:
  postgres:
    container_name: postgres
    image: postgres:17
    volumes:
      - ./postgres/pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - everlock-network
    ports:
      - "5432:5432"
    restart: "no"
    healthcheck:
      test: pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}
      interval: 10s
      timeout: 30s
      retries: 5
